version: "3.9"

services:
  # RabbitMQ service
  RabbitMQ:
    image: rabbitmq:3-management-alpine
    env_file:
      - .env
    container_name: RabbitMQ
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASS}
    ports:
      - 5672:5672 # For sender and consumer connections
      - 15672:15672 # For RabbitMQ GUI
    volumes:
      - ${HOME}/dev-rabbitmq/data/:/var/lib/rabbitmq
      - ${HOME}/dev-rabbitmq/log/:/var/log/rabbitmq
    restart: always
    networks:
      - codeva

networks:
  codeva:
    driver: bridge
